name: Format
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Check formatting
        run: npm run format:check
